# Generated by Django 4.2.7 on 2023-11-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
