# Generated by Django 4.2.7 on 2023-11-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
