# Generated by Django 4.2.7 on 2023-11-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
